Separate message handling; resolve #27
deeprefactoring/deeprefactoring-bot pull request #28
Opened 2019-02-06 20:01 UTC by ilyakaznacheev

Decouple message handling from bot, move message texts into a file

2019-02-06 20:12 UTC, aikikode requested changes

2019-02-06 20:12 UTC, aikikode commented on message.yml
> +  - "Расчет 6%% на Spring Boot или патент?"
Может поправим %% -> % заодно?

2019-02-06 20:12 UTC, aikikode commented on service_test.go
> +		// applyUsername(deeprefactoringbot.RollMessages, user.UserName),
Тут и ниже давайте не будем оставлять закомментированный код, он становится мертвым и про него все забывают, лучше сразу удалить, раз не нужен.

2019-02-06 20:12 UTC, aikikode commented on internal/message/message.go
> +// randomMessage returns a random message from a slise
Опечатка `slise` -> `slice`

2019-02-06 20:14 UTC, ilyakaznacheev commented on service_test.go
> +		// applyUsername(deeprefactoringbot.RollMessages, user.UserName),
Проморгал, уберу

2019-02-06 20:14 UTC, ilyakaznacheev commented on internal/message/message.go
> +// randomMessage returns a random message from a slise
Спасибо, пофикшу

2019-02-06 20:14 UTC, ilyakaznacheev commented on message.yml
> +  - "Расчет 6%% на Spring Boot или патент?"
Сделаю

2019-02-07 14:56 UTC, aikikode approved these changes

2019-02-07 14:59 UTC, aikikode requested changes
`.circleci` changes are also necessary. There should be directives to copy `message.yml` to the server (`{{bot_root}}` directory).

2019-02-07 15:16 UTC, aikikode approved these changes

2019-02-07 15:16 UTC, merged