new greetings and roll phrases
deeprefactoring/deeprefactoring-bot pull request #31
Opened 2019-02-27 10:29 UTC by trubachev

2019-02-27 10:30 UTC, achikin requested changes

2019-02-27 10:30 UTC, achikin commented on messages.yml
> +  - "Я  —  Ʒ  Å  Ę  ƃ  Δ  Ԓ  亡  Я ."
Не, вот это не надо.

2019-02-27 11:53 UTC, trubachev commented on messages.yml
> +  - "Я  —  Ʒ  Å  Ę  ƃ  Δ  Ԓ  亡  Я ."
```suggestion

```

2019-02-27 11:59 UTC, trubachev commented on messages.yml
> +  - "Я  —  Ʒ  Å  Ę  ƃ  Δ  Ԓ  亡  Я ."
fixed int b600c08

2019-03-07 17:45 UTC, achikin approved these changes

2019-03-07 17:46 UTC, merged